### ISSUE TITLE
Budget Sheet - Year/Month in Header

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands-client#177]
# Story
When viewing or editing a budget sheet, the year/month that the budget sheet was created for should be displayed at the top.

### Description
Currently the year and month is using two variables in the budget controller and those variables are initialized as the current year and date, which is helpful when creating a budget sheet. Lines 85 and 86 of the budget controller should be resetting those variables to the month and year on the form, but that is not happening.

**Comment by benaduggan** [comment]
Can you give an example of this not working? When I took a look on staging and prod it seemed to be working as expected?

**Comment by amunn33** [comment]
[This](https://tinyhandsdreamsuite.org/#!/budget/65?isViewing=true) is a form submitted for March 2017 but the top displays May 2017

**Comment by benaduggan** [comment]
ohhh, I see. That is an issue. :stuck_out_tongue: 

I would say that it should be fixed on [line 425](https://github.com/Tiny-Hands/tinyhands-client/blob/master/src/app/budget/form/budget.controller.js#L426)
