### ISSUE TITLE
Budget Sheet Negative Values

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands-client#188]
# Story
Occasionally it is realized that a station received too much money for something on a past report and we want to deduct money on the following report. Because of this, it should be possible to input a negative number in the Misc section that would deduct from the overall value for the next month. If station A receives $20 more in March for a certain section than they should have, it should be possible to put -$20 in the Misc section for station A's April budget sheet in order to make up for that error.

**Comment by benaduggan** [comment]
Why don't we just change the old budget sheet?

**Comment by amunn33** [comment]
That's a good question. The budget sheet is showing how much money we have paid a station for a given month, so if we have already overpaid in March then if we just subtract that amount from the budget sheet it would assume that we can just take the money back (which is difficult to do). Instead, if we give them less for the month of April, it can effectively adjust the overall payment.

**Comment by benaduggan** [comment]
Looks like this is a [backend issue](https://github.com/Tiny-Hands/tinyhands/blob/master/application/budget/models.py). The validation is in the models files itself. Most of the fields in the model use the PositiveIntegerField class, so we want to change that to just IntegerField

**Comment by amunn33** [comment]
Moved to [backend](https://github.com/Tiny-Hands/tinyhands/issues/305).
