### ISSUE TITLE
ID Management issues

### ISSUE THREAD

**Issue by scrishel** [Tiny-Hands/tinyhands-client#192]
Jon identified the following issues with ID Management:
A few things I noticed which you may already be aware of:
- the links to the IRF and VIF forms aren't currently working
- when I scroll to the bottom of a page the screen gets jumpy like it's trying to scroll down further 
- when I tried to use the search feature in the main ID Management page it worked some of the time but other times the thing would keep spinning and never found anything after several minutes. I noticed that if I clicked the sort by name header while it was stuck searching it would sometimes all of a sudden bring up the correct results.
- when sorting with different headers it seemed in some cases to only be sorting the data on that first page, and in others to be sorting additional data that wasn't initially visible (for example, in sorting names either a-z or z-a all of the resulting names started with "a," but when sorting by age names starting with other letters appeared).

The links to IRF and VIF forms not working is known.  Those links will be implemented when the new IRF and VIF forms are available.  The other items are defects that need to be resolved.

**Comment by scrishel** [comment]
After applying the fixes for the initial set of issues, Jon noticed another issue:
One other apparent bug I just noticed is that if you initially go into the Alias Management tab for someone who has aliases, the Form and Form Date fields are blank, but then if you go back to the ID Management page, open an Alias Management page for someone who doesn't have any aliases, and then go back again and into the original or any other Alias Management page with multiple aliases it will show the Form number from the person without aliases that you were most recently looking at.

**Comment by benaduggan** [comment]
@scrishel Should this issue be closed? Or is there more work attached to this? I'm trying to get our waffle board match reality
