### ISSUE TITLE
Remove Scrolling Capability from Number Fields

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands-client#230]
Scrolling on the mouse wheel/track pad while hovering over a number input currently allows for a user to change the value of the number. This feature of Angular doesn't seem to be as useful as it is annoying. I have personally found it difficult when entering budget sheet info and we recently had an error in VIF entry because of it.

**Comment by benaduggan** [comment]
So this is actually the default behavior of an html input field with type="number" and it's pretty hack-y to disable it.

We'd have to basically have some jquery that preventDefaults all of the input fields of that type for the mousescroll event
