### ISSUE TITLE
Expansion Country Individual Account Permissions

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands-client#234]
# Goal
Create interface to display and manipulate permissions set up on [backend](https://github.com/Tiny-Hands/tinyhands/issues/372).

# Details
- Country list should get populated by the country table
- Once country is selected (other than all), station list should be visible and populated by station table (filtering only those associated with selected country)
- Update should be required on each page instead of allowing user to switch between permission type (IRF/VIF/Budget, etc.) and location while requiring front-end to keep track of changes.
- Permissions should cascade down. If user has budget add permission for "Nepal" "All" then when selecting "Nepal" "Birgunj", the budget add permission should be shown.
- Controller should receive a list containing all of the users permissions along with all countries and all stations so that when changing values in the locations drop downs, the user's permissions for that permission group/location would be displayed.

# Questions
- Related to cascading permissions, should removing a permission at a more granular level be disabled? (i.e. If a user has budget add permission for all of Nepal, should removing it for a specific station in Nepal be disabled?)
- Should general account info (email, first/last name, designation) be it's own tab/permission group instead of  a constant part of the page?
- Should permissions have a "granularity" attribute whereby you could decide whether or not a permission can be controlled at a country or station level? For example, the email notifications would only need to go down to a country-based level and allowing station-based granularity would add some unnecessary complications for the permission-checking on that feature. Budget permissions would be another set of permissions that wouldn't require station-specific access. (This affects front & back-end)
# Pictures

#### User with all IRF permission for all countries
![account1](https://user-images.githubusercontent.com/7903547/34432312-4603bb86-ec9e-11e7-8511-b0428544dd4e.png)

#### User with all IRF permissions for Nepal
![account2](https://user-images.githubusercontent.com/7903547/34432402-eb589d90-ec9e-11e7-9abc-96dadd7e9939.png)

#### User with view IRF permission for South Africa
![account3](https://user-images.githubusercontent.com/7903547/34432403-ebfbbcf0-ec9e-11e7-9f0d-3757cf6a15a6.png)

#### User with view and add permission for single station in Nepal
![account4](https://user-images.githubusercontent.com/7903547/34432404-ec9beb9e-ec9e-11e7-8f50-63717c58f30d.png)

#### User with view permission for all stations in Nepal. 
In this case even though the "All Nepal" IRF add permission says no, because the user has IRF add permission for a specific station in Nepal, they would be able to enter IRFs for that station.

![account5](https://user-images.githubusercontent.com/7903547/34432405-ed42f39e-ec9e-11e7-8cbd-a57164c70412.png)

#### User without any budget permissions for their own station
![account6](https://user-images.githubusercontent.com/7903547/34432406-edcf11d0-ec9e-11e7-9202-18c1b45fb8c8.png)

#### User receiving investigative and legal alerts for Nepal
![account7](https://user-images.githubusercontent.com/7903547/34432407-ee64f308-ec9e-11e7-8411-405dead95e8c.png)

**Comment by amunn33** [comment]
@scrishel @benaduggan @andrew-smith3 How does this look?

**Comment by scrishel** [comment]
When a permission is enabled for a user, I would suggest displaying the level at which the permission is enabled rather than just the text "Yes".  So the value displayed would be one of: "Station", "Country" or "Global".  When editing for a specific station, modification of permissions set at a higher level (country or global) should be disabled.  When a permission is enabled at a higher level (country or global), any instances of that same permission enabled at a lower level should be removed.
I would leave the general account information as a constant on the page.
I think it makes sense to add a minimum level to each of the permissions in the permission table on the server that value would be "Station", "Country" or "Global".

**Comment by andrew-smith3** [comment]
In regards to the second question, what would you think of going with a master-detail type of view, similar to github's settings page? 
![image](https://user-images.githubusercontent.com/5403519/34456172-158709ac-ed5e-11e7-9b95-6db5c230d1e2.png)
We could have different sections with headers in the master list for user info and user permissions. Clicking on them could then show the relevant detail view, either the account info or the permissions controls from Austin's images. Any thoughts?

**Comment by amunn33** [comment]
I do like the idea of having this sort of a master-detail view, but would there mostly just be the two big sections?

Hang with me on this crazy idea but I found this [multi-select button](http://dotansimha.github.io/angularjs-dropdown-multiselect/docs/#/main) and am trying to figure out what it would look like for us to use it. I think it has the potential to really simplify the UI of this selection but it would probably take a while to get it implemented correctly (if it is possible at all). The main features that I could see being useful here are the disabling, grouping, and searching. If we were to do this I would imagine using one multi-select per permission on the page.

What do you guys think of this?

**Comment by scrishel** [comment]
For the multi-select button, are you thinking of something like the following?
![image](https://user-images.githubusercontent.com/12170592/34468951-f84e71c4-eee1-11e7-8103-118df01c8a01.png)

**Comment by amunn33** [comment]
Basically, does that make more sense?

I was thinking it might even be possible to have all of the options in a single dropdown and use the grouping mechanism to have the options look something like:
#### Global
All
#### Country
Nepal
South Africa
Bangladesh
Thailand
#### Nepal
Bhairahawa
Birgunj
Tikapur
..
#### South Africa
Johannesburg
..

**Comment by scrishel** [comment]
The problem with having all of the options in a single dropdown is that one would be able to select multiple items that do not really make sense.  For example, you could select "All" and also select a country or station.  Also a country and a contained station.
How would the application respond if the user selected a combination like that.

**Comment by amunn33** [comment]
Well upon each selection I believe you can have it call a function, in which case you could have it run a check to disable options that wouldn't make sense.

**Comment by scrishel** [comment]
Hmm.  Maybe.  I will experiment and see if I can get something to work...

**Comment by benaduggan** [comment]
Is this considered done at this point?
