### ISSUE TITLE
Interceptee View Functionality

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands-client#269]
## Acceptance Requirements
- [ ] Selecting an interceptee card should take the user to that interceptee's detail [screen.](https://github.com/Tiny-Hands/tinyhands-client/issues/260)
- [ ] Selecting the '+' should take the user to a blank interceptee detail screen.

## Mockup
![interceptees interceptee view](https://user-images.githubusercontent.com/7903547/38808483-1a0a75ae-41a0-11e8-9550-af0e09f9323e.png)

**Comment by benaduggan** [comment]
Oh, I'm confused on how these stories are written... So I'll comment this here too. Do we want to make these modals instead of moving to a new page?

**Comment by amunn33** [comment]
So the base page would be this and by clicking the interceptees, a modal with the interceptee detail would pop up?

**Comment by scrishel** [comment]
If we make the interceptee detail a modal, will it be difficult to open sub-modals for things like create new address?  When I was working on ID Management, I had difficulty opening a modal within another modal in Angular.  Perhaps that is just my lack of experience with Angular?
