### ISSUE TITLE
Location and Staff Dropdown Inputs

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands-client#270]
## Acceptance Critieria
- [ ] Location and Staff input boxes should act like regular text boxes (can allow free input) but include a dropdown that can be used to select preset values which will populate the box.
- [ ] If text has been input into a Location or Staff box and a value is selected in the corresponding dropdown, the input should be cleared and populated with the selected value.
- [ ] Should allow one location to be selected
- [ ] Should use the following API to retrieve list of locations that location dropdown is loaded with: '/api/border-station/' + stationID + '/location/'
- [ ] Should allow multiple staff members to be selected, using a comma to separate each value
- [ ] Should use the following API to retrieve list of staff members that staff dropdown is loaded with: '/api/border-station/' + stationID + '/staff/'

## Mockups

*Selecting Location*
![top box location selected](https://user-images.githubusercontent.com/7903547/38195314-aa18d8fc-369c-11e8-9d1b-863226b4b21a.png)

*Selecting Staff*
![top box staff name selected](https://user-images.githubusercontent.com/7903547/38195310-a757c402-369c-11e8-9551-f0e5e6ae3221.png)

## Location JSON
````
[
    {
        "id": 52,
        "name": "Railyard",
        "latitude": 27.6826184,
        "longitude": 83.865645,
        "border_station": 1
    },
    {
        "id": 51,
        "name": "Main Street Bus Stop",
        "latitude": 27.6008535,
        "longitude": 83.5569871,
        "border_station": 1
    },
    {
        "id": 50,
        "name": "Westmont Border",
        "latitude": 27.5801442,
        "longitude": 83.6428701,
        "border_station": 1
    }
]
````

## Staff JSON
````
[
    {
        "id": 24,
        "email": "",
        "first_name": "Frank",
        "last_name": "Hardy",
        "phone": "9993214563",
        "position": "Safety / Paralegal Coordinator",
        "receives_money_distribution_form": false,
        "border_station": 2
    },
    {
        "id": 25,
        "email": "nancy_drew@yahoo.com",
        "first_name": "Nancy",
        "last_name": "Drew",
        "phone": "99984613240",
        "position": "Station Manager / Data Coordinator",
        "receives_money_distribution_form": false,
        "border_station": 2
    },
    {
        "id": 26,
        "email": "",
        "first_name": "Sherlock",
        "last_name": "Holmes",
        "phone": "9996228266",
        "position": "Admin / Accounting Coordinator",
        "receives_money_distribution_form": false,
        "border_station": 2
    },
    {
        "id": 29,
        "email": "",
        "first_name": "Hercule",
        "last_name": "Poirot",
        "phone": "9991031633",
        "position": "Legal Advisor",
        "receives_money_distribution_form": false,
        "border_station": 2
    }
]
````

**Comment by benaduggan** [comment]
@scrishel @amunn33 are we sure we want these to be free text as well? I get the reason for location names to be free text, but even then I'd think we would want them to enter in a new location for their border station even if it's just a placeholder at that time so that we have links to objects in the DB rather than text that may or may not be related to real objects

**Comment by amunn33** [comment]
Yeah I definitely see the value there too. So would there be a modal to be able to add new station locations as well or if they entered a new one would it just go into as a new location without other details?

**Comment by benaduggan** [comment]
I was thinking we could make it similar to the address fields? And depending on the use case, we don't have to enforce them to enter all of the data if they don't have GPS coordinates or anything. I just think we'd want to save them as objects

**Comment by amunn33** [comment]
Yeah, that could be a useful connection to make especially because we're already storing those as objects.

**Comment by bsell93** [comment]
@amunn33 or @benaduggan or @andrew-smith3 we have been building this portion out and noticed that the endpoints for staff and location require a border station id. As of now I don't believe there is a way to know which border station id to use here. Are we going to be adding a dropdown to specify the border station to then allow selection of location and staff? Or is there some magic id just floating around that we don't know about?

**Comment by amunn33** [comment]
Yeah, it's very hacky now.  We're planning to have them select a station
beforehand similar to the budget calc sheet so you should be able to assume
the id is present.

**Comment by amunn33** [comment]
@bsell93 Does that make sense? If you check out [this](https://github.com/Tiny-Hands/tinyhands-client/issues/279) issue, they'll be selecting the station ahead so the controller should know the station id.

**Comment by bsell93** [comment]
@amunn33 yeah that makes sense! Sounds good to me! I don't think we will be handling that. I can make a note about it, which I am planning on making notes of things that might need to be address or added for you guys to have some reference points.

**Comment by benaduggan** [comment]
@amunn33 Do we know how we'll handle if they want to add a person who isn't attached to the station?

**Comment by bsell93** [comment]
@benaduggan & @amunn33 it would be nice to have a component that is a button that when clicked opens a modal that will allow you to create a staff then. It seems like this is a piece of functionality that will be needed in multiple places.
