### ISSUE TITLE
List pages should have sticky headers

### ISSUE THREAD

**Issue by benaduggan** [Tiny-Hands/tinyhands-client#72]
Any list view in the site should have "sticky headers". For example, on the accounts list page, the labels for the columns should scroll with you down the page so you can see the headers even when you are beyond the reach of the page.

This applies to the following pages:
- Accounts List
- Access Control
- Access Default
- Addresses pages
- Budget List
- IRF/VIF Lists

**Comment by jsouthwo** [comment]
@andrewfennig @jahudlow Can any information be removed or shortened on the Accounts List page? Currently our table is overrunning its borders and that's causing this to 
![fail](https://cloud.githubusercontent.com/assets/5342295/20242893/076239fa-a90d-11e6-8e6c-1a54a6416413.png) because the table is forced inside its boundary, causing columns to be superimposed on each other.

**Comment by jsouthwo** [comment]
I was thinking of stripping the time from the `Date Created` and `Last Login` columns so it's just the date, and perhaps removing the email address.

**Comment by jahudlow** [comment]
That's fine with me if the times are removed. Same with the e-mail addresses, since I assume we'll still be able to see them in "Edit" if we need to which should be sufficient.

**Comment by jsouthwo** [comment]
@benaduggan @andrew-smith3 The code is working. Not sure how to test this though... is it necessary/possible?

**Comment by benaduggan** [comment]
I'm not really sure how to test it either.. I'm okay without testing it. I did notice the build failed the last time you pushed though. The bower install failed with `bower ENOTFOUND     Package angular-floatThead not found`

**Comment by jsouthwo** [comment]
Is there a way for me to see the build results?

**Comment by benaduggan** [comment]
So I just checked on Codeship, and it looks like Bryant is the "team manager" and is the only one who can invite people to the group. I should see him tomorrow at work, so I'll try to get you added tomorrow for sure!

**Comment by jsouthwo** [comment]
@bsell93 Hook me up!

**Comment by benaduggan** [comment]
@jsouthwo I slacked you about it, I have control now, but I'm not sure what email you want me to use and didn't think you would want to put that on here

**Comment by jsouthwo** [comment]
Oh. My bad... didn't see it. I've replied now.
