### ISSUE TITLE
Save for Later list is not clearing when forms are submitted

### ISSUE THREAD

**Issue by benaduggan** [Tiny-Hands/tinyhands-client#79]
We have rest endpoints to check if an IRF or VIF with a number exists in the database. If they do, then the "saved for later" form should be deleted from local storage. I think this should be done in the list controllers for now, but in the future should live in the creation pages once they are made in the angular client.

[Trello card.](https://trello.com/c/Aguz3sUj/73-save-for-later-list-is-not-clearing-when-forms-are-submitted)

Originally logged [here](https://github.com/Tiny-Hands/tinyhands/issues/196)

**Comment by amunn33** [comment]
Still not clearing saved form when form is submitted. I remember we talked about this but thought that it was going to work on staging.

**Comment by benaduggan** [comment]
I think I found the issue. There are 404s happening because of the URLs defined in dataentry

EG. https://staging.tinyhandsdreamsuite.org/data-entry/irfs/irfExists/BHD999

I think I messed up this Regex by accident. `irfs/irfExists/([A-Z]{3}[0-9]+[A-Z]+)`

So it's not matching BHD999 because there aren't letters after it. It needs to be changed to an asterisk

**Comment by amunn33** [comment]
That's right, forgot about that.

**Comment by benaduggan** [comment]
This is being fixed here, so if you could do a small code review on the couple lines I changed, then we can move this over and test it out on staging https://github.com/Tiny-Hands/tinyhands/pull/233
